version: '3'

services: 
  walmart-challenge:
    container_name: search-app
    restart: always
    build: .
    ports:
      - "5000:3000"
    links: 
      - mongo
    volumes:
      - .:/usr/src/app
  mongo:
    container_name: walmart-products
    image: mongo
    ports:
      - "27017:27017"